server:
  port: 7777

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  datasource:
   driver-class-name: org.hsqldb.jdbc.JDBCDriver    
   url: jdbc:hsqldb:mem:tkndb;DB_CLOSE_DELAY=-1
   username: sa
   password: 1243
  jpa:
   hibernate.ddl-auto:create

    
security:
  basic:
    enabled: false
  oauth2:
    resource:
      userInfoUri: http://localhost:7777/credentia
oauth:
   privateKey: T439jLWJ6MpGa1OCAEoeMUF3B8dPKgOsr5DN8lUqthE8ltkoGWqndqbLogEg4dfMf0uRjtsDH6Ue3R0K    
    
  