server:
  port: 50009
  
spring:
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:rackdb;DB_CLOSE_DELAY=-1
    username: sa
    password: 123
  jpa:
    hibernate:
       ddl-auto: update
  oauth2:
    resource:
      userInfoUri: http://localhost:7777/credential
  sql:
   init:
    schema-locations: classpath*:db/schema-hsqldb.sql
    data-locations: classpath*:db/data-hsqldb.sql     
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health      
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
oauth:
  privateKey: T439jLWJ6MpGa1OCAEoeMUF3B8dPKgOsr5DN8lUqthE8ltkoGWqndqbLogEg4dfMf0uRjtsDH6Ue3R0K